# Generated by Django 5.2.3 on 2025-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='name',
            field=models.CharField(default='Sivaguru M', help_text='Enter Your Name', max_length=25),
        ),
    ]
