# Generated by Django 5.2.3 on 2025-06-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_github_link_alter_project_live_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
